name: Mainely Mesh
favicon: null
layout_spectrum: 0.15165954874828458
typography_spectrum: 0.2514555046800524
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7805540177505463
  lightness: 0.0254540650639683
  saturation: 0.29583481256850064
  rhythmicContrast: 0.565133368363604
purpose: []
